project:
  type: website
  output-dir: docs

website:
  title: "Kiril Zvezdarov's Blog"
  site-url: https://kirilzvezdarov.com
  description: "Kiril Zvezdarov's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kzvezdarov
      - icon: rss
        href: index.xml
    left:
      - fantasygp_dashboard.ipynb
format:
  html:
    theme: simplex
    css: styles.css
