project:
  type: website
  output-dir: docs

website:
  title: "kzvezdarov.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kzvezdarov
format:
  html:
    theme: simplex
    css: styles.css
